services:
  db:
    image: postgres:16-alpine
    restart: 'no'
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: stream
      POSTGRES_DB: db_stream
    volumes:
      - storage_stream:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
volumes:
  storage_stream:
    external: true